/*
 * Employee
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.employeeapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;
/**
 * AddEmployeeRs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-11-13T23:10:04.450-05:00[America/New_York]")
public class AddEmployeeRs implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("employee")
  private AddEmployeeRsEmployee employee = null;

  public AddEmployeeRs employee(AddEmployeeRsEmployee employee) {
    this.employee = employee;
    return this;
  }

   /**
   * Get employee
   * @return employee
  **/
  @Valid
  @Schema(description = "")
  public AddEmployeeRsEmployee getEmployee() {
    return employee;
  }

  public void setEmployee(AddEmployeeRsEmployee employee) {
    this.employee = employee;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddEmployeeRs addEmployeeRs = (AddEmployeeRs) o;
    return Objects.equals(this.employee, addEmployeeRs.employee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddEmployeeRs {\n");
    
    sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
